export const customerOrganizations = [
  { name: 'NVIDIA', sources: ['https://cdn.simpleicons.org/nvidia/76B900', 'https://www.google.com/s2/favicons?domain=nvidia.com&sz=128'] },
  { name: 'PepsiCo', sources: ['https://commons.wikimedia.org/wiki/Special:FilePath/Pepsico%20logo%20%282%29.svg', 'https://www.google.com/s2/favicons?domain=pepsico.com&sz=128'] },
  { name: 'DHL', sources: ['https://cdn.simpleicons.org/dhl/D40511', 'https://www.google.com/s2/favicons?domain=dhl.com&sz=128'] },
  { name: 'Barrett Distribution Centers', sources: ['https://www.google.com/s2/favicons?domain=barrettdistribution.com&sz=128', 'https://logo.clearbit.com/barrettdistribution.com?size=512'] },
  { name: 'DSV', sources: ['https://commons.wikimedia.org/wiki/Special:FilePath/DSV%20Logo.svg', 'https://www.google.com/s2/favicons?domain=dsv.com&sz=128'] },
  { name: 'GEODIS', sources: ['https://www.google.com/s2/favicons?domain=geodis.com&sz=128', 'https://logo.clearbit.com/geodis.com?size=512'] },
  { name: 'Glossier', sources: ['https://www.google.com/s2/favicons?domain=glossier.com&sz=128', 'https://logo.clearbit.com/glossier.com?size=512'] },
  { name: 'ID Logistics', sources: ['https://images.seeklogo.com/logo-png/50/1/id-logistics-logo-png_seeklogo-502829.png', 'https://www.google.com/s2/favicons?domain=id-logistics.com&sz=128'] },
  { name: 'IKEA', sources: ['https://cdn.simpleicons.org/ikea/0058A3', 'https://www.google.com/s2/favicons?domain=ikea.com&sz=128'] },
  { name: 'NFI', sources: ['https://cdn.freebiesupply.com/logos/large/2x/nfi-industries-logo-png-transparent.png', 'https://www.google.com/s2/favicons?domain=nfiindustries.com&sz=128'] },
  { name: 'Ashley Furniture', sources: ['https://commons.wikimedia.org/wiki/Special:FilePath/Ashley%20logo%202022.svg', 'https://www.google.com/s2/favicons?domain=ashleyfurniture.com&sz=128'] },
  { name: 'Averitt', sources: ['https://www.averitt.com/hs-fs/hubfs/Averitt_logo_250_PNG.png?name=Averitt_logo_250_PNG.png&width=250', 'https://www.google.com/s2/favicons?domain=averitt.com&sz=128'] },
  { name: 'Ryder', sources: ['/ryder-logo.png'] },
  { name: 'WESCO', sources: ['https://www.google.com/s2/favicons?domain=wesco.com&sz=128', 'https://logo.clearbit.com/wesco.com?size=512'] },
  { name: 'GXO', sources: ['https://www.google.com/s2/favicons?domain=gxo.com&sz=128', 'https://logo.clearbit.com/gxo.com?size=512'] },
  { name: 'Chobani', sources: ['https://commons.wikimedia.org/wiki/Special:FilePath/Chobani%20logo.svg', 'https://www.google.com/s2/favicons?domain=chobani.com&sz=128'] },
  { name: 'Dell', sources: ['https://cdn.simpleicons.org/dell/0672CB', 'https://www.google.com/s2/favicons?domain=dell.com&sz=128'] },
  { name: 'Maersk', sources: ['https://cdn.simpleicons.org/maersk/42B0D5', 'https://www.google.com/s2/favicons?domain=maersk.com&sz=128'] },
] as const
